{{- if $.Values.default.externalSecrets }}
{{- if $.Values.default.externalSecrets.volumeMount }}
{{- range $secret := $.Values.default.externalSecrets.volumeMount.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ (print (include "helper.name" $) "-" ($secret.secretName)) }}
  namespace: {{ $.Release.Namespace }}
  {{- if or $.Values.default.labels.all $.Values.default.labels.secrets .labels }}
  labels:
  {{- (include "helper.labels" $) | nindent 4 }}
  {{- with .labels }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with $.Values.default.labels.secrets }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
  {{- if or $.Values.default.labels.all $.Values.default.labels.secrets .annotations }}
  annotations:
  {{- (include "helper.annotations" $) | nindent 4 }}
  {{- with $.Values.default.annotations.secrets }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- with .annotations }}
  {{- toYaml . | nindent 4}}
  {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ default "5m" $secret.refreshInterval }}
  secretStoreRef:
    name: {{ required "SecretStoreRef not provided" $secret.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ (print (include "helper.name" $) "-" ($secret.secretName)) }}
    creationPolicy: Owner
  data:
  {{- range $secret.data }}
  - secretKey: {{ .fileName  }} 
    remoteRef:
      key: {{ .secretKey }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
