{{- range $deployments := $.Values.deployments }}
{{- $deployment := . -}}
{{- if .service }}
{{- range $service := .service.ports}}
{{- if and $service.ingress $service.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helper.fullname" (merge $deployment $) }}
  namespace: {{ $.Release.Namespace }}
  annotations:
{{- range $key, $value := $service.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: alb
  rules:
{{- range $rule := $service.ingress.rules }}
    - host: {{ $rule.host }}
      http:
        paths:
{{- range $path := $rule.http.paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType }}
            backend:
              service:
                name: {{ $path.backend.service.name }}
                port:
                  number: {{ $path.backend.service.port.number }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
