apiVersion: v1
kind: ConfigMap
metadata:
  name: lentra-los-config
  namespace: atlas-dev
data:
  FLASK_ENV: "development"
  LOS_DATABASE_URL: "mysql+pymysql://admininfra:Atlas9876%23infra@kmatlas.cpica6giy2g3.ap-south-1.rds.amazonaws.com/uat_lentra_devops"
  LOS_AWS_REGION: "ap-south-1"
  LOS_LLM_QUEUE: "uat-lentra-los-llmservice"
  LOS_POSTLLM_QUEUE: "uat-lentra-los-postllm"
  LOS_CROSSCHECKS_QUEUE: "uat-lentra-los-crosschecks"
  LOS_CALLBACK_QUEUE: "uat-lentra-los-callback"
  LOS_COUNTER_QUEUE: "uat-lentra-los-counter"
  LOS_UPLOAD_QUEUE: "uat-lentra-los-upload"
  LOS_ABCL_UPLOAD_QUEUE: "uat-los-abcl-upload"
  LOS_ABCL_LLM_QUEUE: "uat-los-abcl-llmservice"
  LOS_ABCL_COUNTER_QUEUE: "uat-los-abcl-counter"
  LOS_ABCL_CALLBACK_QUEUE: "uat-los-abcl-callback"
  REDIS_PORT: "6379"
  SAGE_API_BASE_URL: "http://3.6.238.4"
  ADDRESS_API: "http://address-service:8000/v1/address/match"
  LOS_LENTRA_TENENT_ID: "4437"
  LOS_LENTRA_APPLICATION: "dummy"
  LOS_LENTRA_INSTITUTION_ID: "9630"
  LOS_LENTRA_INSTITUTION_NAME: "PFL"
  LOS_BUCKET_NAME: "uat-lentra-los"
